namespace AudioControlApp.Localization;

internal static class Strings
{
    public static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        // Layout names
        ["Layout_Mono"] = "Mono (1.0)",
        ["Layout_Stereo"] = "Stereo (2.0)",
        ["Layout_Quad"] = "Quadraphonic (4.0)",
        ["Layout_Surround"] = "Surround (4.0, rear center)",
        ["Layout_51"] = "5.1 Surround",
        ["Layout_51Side"] = "5.1 Surround (side speakers)",
        ["Layout_71"] = "7.1 Surround",
        ["Layout_71Wide"] = "7.1 Wide",
        ["Layout_Custom"] = "Custom {0} (mask 0x{1:X})",

        // Tray
        ["Status_NoDevice"] = "No active output device",
        ["Status_FallbackSuffix"] = "(configured device not found – using the default device)",
        ["Status_Physical"] = "Speaker configuration: {0}",
        ["Menu_Current"] = "Current: {0}",
        ["Menu_AutoSwitch"] = "Automatic switching",
        ["Menu_Startup"] = "Start with Windows",
        ["Menu_Settings"] = "Settings…",
        ["Menu_SoundPanel"] = "Windows sound control panel…",
        ["Menu_Exit"] = "Exit",
        ["Reason_Manual"] = "Switched manually",
        ["Reason_Fallback"] = "No rule matches – back to the default layout",
        ["Reason_RuleRunning"] = "{0} is running",
        ["Reason_RuleForeground"] = "{0} is in the foreground",
        ["Reason_CommandLine"] = "Command line",
        ["Msg_SwitchedTitle"] = "Switched to {0}",
        ["Msg_SwitchFailed"] = "Could not change the speaker layout",
        ["Msg_StartupFailed"] = "Could not change the startup setting",
        ["Msg_HotkeyFailed"] = "The hotkey {0} is already in use by another application.",
        ["Msg_UnknownLayout"] = "Unknown layout: {0}",
        ["Msg_AlreadyRunning"] = "AudioControlApp is already running but did not respond.",

        // Buttons
        ["Btn_OK"] = "OK",
        ["Btn_Cancel"] = "Cancel",
        ["Btn_Apply"] = "Apply",
        ["Btn_Refresh"] = "Refresh",
        ["Btn_Add"] = "Add…",
        ["Btn_Edit"] = "Edit…",
        ["Btn_Remove"] = "Remove",
        ["Btn_Up"] = "Move up",
        ["Btn_Down"] = "Move down",

        // Settings window
        ["Settings_Title"] = "AudioControlApp settings",
        ["Tab_General"] = "General",
        ["Tab_Auto"] = "Automatic switching",
        ["Tab_Layouts"] = "Layouts",
        ["Group_Device"] = "Output device",
        ["Device_FollowDefault"] = "Follow the Windows default output device",
        ["Device_Missing"] = "not connected",
        ["Device_StatusFormat"] = "{0}\nCurrent format: {1}  –  {2}",
        ["Group_Tray"] = "Tray icon",
        ["Tray_LeftClick"] = "Left-click on the tray icon toggles between",
        ["Tray_And"] = "and",
        ["Tray_Notify"] = "Show a notification when the layout changes",
        ["Tray_Hotkey"] = "Global toggle hotkey:",
        ["Tray_HotkeyHint"] = "(click, then press a key combination; Backspace clears)",
        ["Hotkey_None"] = "None",
        ["Group_Startup"] = "Startup",
        ["Startup_Enable"] = "Start with Windows (at logon)",
        ["Startup_State_Enabled"] = "Registered in the current user's Run key.",
        ["Startup_State_Disabled"] = "Not registered.",
        ["Startup_State_Blocked"] = "Registered, but disabled in Task Manager › Startup apps. Re-check the box to enable it again.",
        ["Startup_State_Stale"] = "A Run entry exists but points at another location. Re-check the box to update it.",
        ["Group_Misc"] = "Miscellaneous",
        ["Misc_Language"] = "Language:",
        ["Misc_Log"] = "Write a log file",
        ["Misc_OpenLog"] = "Open log folder",
        ["Misc_OpenConfig"] = "Open settings folder",

        // Auto switch tab
        ["Auto_Enable"] = "Enable automatic switching",
        ["Auto_Explain"] = "Rules are checked from top to bottom; the first match wins. While a matching program is running (or in the foreground) its layout is applied. When nothing matches, the fallback layout is applied. A manual switch is kept until the rule state changes again.",
        ["Auto_ColProcess"] = "Program",
        ["Auto_ColTrigger"] = "Trigger",
        ["Auto_ColLayout"] = "Layout",
        ["Auto_ColComment"] = "Comment",
        ["Auto_Fallback"] = "When no rule matches:",
        ["Auto_FallbackNone"] = "Do nothing",
        ["Auto_Interval"] = "Check every",
        ["Auto_IntervalUnit"] = "seconds",

        // Rule editor
        ["Rule_Title"] = "Rule",
        ["Rule_Process"] = "Program:",
        ["Rule_ProcessHint"] = "Executable name, e.g. game.exe. Wildcards * and ? are allowed.",
        ["Rule_Browse"] = "Browse…",
        ["Rule_PickRunning"] = "Running…",
        ["Rule_Trigger"] = "Trigger:",
        ["Trigger_Running"] = "While running",
        ["Trigger_Foreground"] = "While in the foreground",
        ["Rule_Layout"] = "Layout:",
        ["Rule_Comment"] = "Comment:",
        ["Rule_Enabled"] = "Rule enabled",
        ["Rule_ProcessRequired"] = "Please enter a program name.",

        // Process picker
        ["Picker_Title"] = "Choose a running program",
        ["Picker_ColProcess"] = "Program",
        ["Picker_ColWindow"] = "Window title",
        ["Picker_ShowAll"] = "Show background processes too",

        // Layouts tab
        ["Layouts_Explain"] = "Checked layouts appear in the tray menu. The device is probed for support using its current sample rate and bit depth (the same test the Windows Sound control panel uses).",
        ["Layouts_Supported"] = "✓ supported",
        ["Layouts_Unsupported"] = "✗ not accepted by the device",
        ["Layouts_Probe"] = "Probe device support",
        ["Layouts_Probing"] = "Probing…",
        ["Layouts_ProbeDone"] = "Probe complete.",
        ["Layouts_CustomLabel"] = "Custom channel mask:",
        ["Layouts_AddCustom"] = "Add",
        ["Layouts_InvalidMask"] = "Enter a channel mask such as 0x63F (hexadecimal) or 1599 (decimal).",
        ["Layouts_NeedOne"] = "Select at least one layout for the tray menu.",
    };

    public static readonly IReadOnlyDictionary<string, string> SimplifiedChinese = new Dictionary<string, string>
    {
        ["Layout_Mono"] = "单声道 (1.0)",
        ["Layout_Stereo"] = "立体声 (2.0)",
        ["Layout_Quad"] = "四声道 (4.0)",
        ["Layout_Surround"] = "环绕 (4.0，后中置)",
        ["Layout_51"] = "5.1 环绕声",
        ["Layout_51Side"] = "5.1 环绕声（侧置音箱）",
        ["Layout_71"] = "7.1 环绕声",
        ["Layout_71Wide"] = "7.1 宽前置",
        ["Layout_Custom"] = "自定义 {0}（掩码 0x{1:X}）",

        ["Status_NoDevice"] = "没有可用的输出设备",
        ["Status_FallbackSuffix"] = "（未找到指定设备，正在使用默认设备）",
        ["Status_Physical"] = "扬声器配置：{0}",
        ["Menu_Current"] = "当前：{0}",
        ["Menu_AutoSwitch"] = "自动切换",
        ["Menu_Startup"] = "开机启动",
        ["Menu_Settings"] = "设置…",
        ["Menu_SoundPanel"] = "Windows 声音控制面板…",
        ["Menu_Exit"] = "退出",
        ["Reason_Manual"] = "手动切换",
        ["Reason_Fallback"] = "没有匹配的规则，恢复默认布局",
        ["Reason_RuleRunning"] = "{0} 正在运行",
        ["Reason_RuleForeground"] = "{0} 位于前台",
        ["Reason_CommandLine"] = "命令行",
        ["Msg_SwitchedTitle"] = "已切换到 {0}",
        ["Msg_SwitchFailed"] = "无法更改扬声器布局",
        ["Msg_StartupFailed"] = "无法更改开机启动设置",
        ["Msg_HotkeyFailed"] = "热键 {0} 已被其他程序占用。",
        ["Msg_UnknownLayout"] = "未知的布局：{0}",
        ["Msg_AlreadyRunning"] = "AudioControlApp 已在运行，但没有响应。",

        ["Btn_OK"] = "确定",
        ["Btn_Cancel"] = "取消",
        ["Btn_Apply"] = "应用",
        ["Btn_Refresh"] = "刷新",
        ["Btn_Add"] = "添加…",
        ["Btn_Edit"] = "编辑…",
        ["Btn_Remove"] = "删除",
        ["Btn_Up"] = "上移",
        ["Btn_Down"] = "下移",

        ["Settings_Title"] = "AudioControlApp 设置",
        ["Tab_General"] = "常规",
        ["Tab_Auto"] = "自动切换",
        ["Tab_Layouts"] = "布局",
        ["Group_Device"] = "输出设备",
        ["Device_FollowDefault"] = "跟随 Windows 默认输出设备",
        ["Device_Missing"] = "未连接",
        ["Device_StatusFormat"] = "{0}\n当前格式：{1}  –  {2}",
        ["Group_Tray"] = "托盘图标",
        ["Tray_LeftClick"] = "左键单击托盘图标时在以下两种布局间切换",
        ["Tray_And"] = "和",
        ["Tray_Notify"] = "布局变化时显示通知",
        ["Tray_Hotkey"] = "全局切换热键：",
        ["Tray_HotkeyHint"] = "（点击后按下组合键；Backspace 清除）",
        ["Hotkey_None"] = "无",
        ["Group_Startup"] = "启动",
        ["Startup_Enable"] = "开机自动启动（登录时）",
        ["Startup_State_Enabled"] = "已注册到当前用户的 Run 项。",
        ["Startup_State_Disabled"] = "未注册。",
        ["Startup_State_Blocked"] = "已注册，但在“任务管理器 › 启动应用”中被禁用。重新勾选即可再次启用。",
        ["Startup_State_Stale"] = "存在 Run 项，但指向其他位置。重新勾选即可更新。",
        ["Group_Misc"] = "其他",
        ["Misc_Language"] = "语言：",
        ["Misc_Log"] = "写入日志文件",
        ["Misc_OpenLog"] = "打开日志文件夹",
        ["Misc_OpenConfig"] = "打开设置文件夹",

        ["Auto_Enable"] = "启用自动切换",
        ["Auto_Explain"] = "规则自上而下匹配，第一条命中的规则生效。当匹配的程序正在运行（或位于前台）时应用其布局；没有任何规则匹配时应用回退布局。手动切换会一直保持，直到规则状态再次变化。",
        ["Auto_ColProcess"] = "程序",
        ["Auto_ColTrigger"] = "触发条件",
        ["Auto_ColLayout"] = "布局",
        ["Auto_ColComment"] = "备注",
        ["Auto_Fallback"] = "没有规则匹配时：",
        ["Auto_FallbackNone"] = "不做任何操作",
        ["Auto_Interval"] = "检查间隔",
        ["Auto_IntervalUnit"] = "秒",

        ["Rule_Title"] = "规则",
        ["Rule_Process"] = "程序：",
        ["Rule_ProcessHint"] = "可执行文件名，例如 game.exe。支持通配符 * 和 ?。",
        ["Rule_Browse"] = "浏览…",
        ["Rule_PickRunning"] = "运行中…",
        ["Rule_Trigger"] = "触发条件：",
        ["Trigger_Running"] = "运行时",
        ["Trigger_Foreground"] = "位于前台时",
        ["Rule_Layout"] = "布局：",
        ["Rule_Comment"] = "备注：",
        ["Rule_Enabled"] = "启用此规则",
        ["Rule_ProcessRequired"] = "请输入程序名。",

        ["Picker_Title"] = "选择正在运行的程序",
        ["Picker_ColProcess"] = "程序",
        ["Picker_ColWindow"] = "窗口标题",
        ["Picker_ShowAll"] = "同时显示后台进程",

        ["Layouts_Explain"] = "勾选的布局会显示在托盘菜单中。程序会以设备当前的采样率和位深检测其是否支持各布局（与 Windows 声音控制面板使用相同的测试）。",
        ["Layouts_Supported"] = "✓ 支持",
        ["Layouts_Unsupported"] = "✗ 设备不接受",
        ["Layouts_Probe"] = "检测设备支持情况",
        ["Layouts_Probing"] = "检测中…",
        ["Layouts_ProbeDone"] = "检测完成。",
        ["Layouts_CustomLabel"] = "自定义声道掩码：",
        ["Layouts_AddCustom"] = "添加",
        ["Layouts_InvalidMask"] = "请输入声道掩码，例如 0x63F（十六进制）或 1599（十进制）。",
        ["Layouts_NeedOne"] = "请至少为托盘菜单选择一种布局。",
    };

    public static readonly IReadOnlyDictionary<string, string> TraditionalChinese = new Dictionary<string, string>
    {
        ["Layout_Mono"] = "單聲道 (1.0)",
        ["Layout_Stereo"] = "立體聲 (2.0)",
        ["Layout_Quad"] = "四聲道 (4.0)",
        ["Layout_Surround"] = "環繞 (4.0，後中置)",
        ["Layout_51"] = "5.1 環繞聲",
        ["Layout_51Side"] = "5.1 環繞聲（側置喇叭）",
        ["Layout_71"] = "7.1 環繞聲",
        ["Layout_71Wide"] = "7.1 寬前置",
        ["Layout_Custom"] = "自訂 {0}（遮罩 0x{1:X}）",

        ["Status_NoDevice"] = "沒有可用的輸出裝置",
        ["Status_FallbackSuffix"] = "（找不到指定裝置，正在使用預設裝置）",
        ["Status_Physical"] = "喇叭配置：{0}",
        ["Menu_Current"] = "目前：{0}",
        ["Menu_AutoSwitch"] = "自動切換",
        ["Menu_Startup"] = "開機啟動",
        ["Menu_Settings"] = "設定…",
        ["Menu_SoundPanel"] = "Windows 音效控制台…",
        ["Menu_Exit"] = "結束",
        ["Reason_Manual"] = "手動切換",
        ["Reason_Fallback"] = "沒有符合的規則，恢復預設配置",
        ["Reason_RuleRunning"] = "{0} 正在執行",
        ["Reason_RuleForeground"] = "{0} 位於前景",
        ["Reason_CommandLine"] = "命令列",
        ["Msg_SwitchedTitle"] = "已切換至 {0}",
        ["Msg_SwitchFailed"] = "無法變更喇叭配置",
        ["Msg_StartupFailed"] = "無法變更開機啟動設定",
        ["Msg_HotkeyFailed"] = "快速鍵 {0} 已被其他程式佔用。",
        ["Msg_UnknownLayout"] = "未知的配置：{0}",
        ["Msg_AlreadyRunning"] = "AudioControlApp 已在執行，但沒有回應。",

        ["Btn_OK"] = "確定",
        ["Btn_Cancel"] = "取消",
        ["Btn_Apply"] = "套用",
        ["Btn_Refresh"] = "重新整理",
        ["Btn_Add"] = "新增…",
        ["Btn_Edit"] = "編輯…",
        ["Btn_Remove"] = "刪除",
        ["Btn_Up"] = "上移",
        ["Btn_Down"] = "下移",

        ["Settings_Title"] = "AudioControlApp 設定",
        ["Tab_General"] = "一般",
        ["Tab_Auto"] = "自動切換",
        ["Tab_Layouts"] = "配置",
        ["Group_Device"] = "輸出裝置",
        ["Device_FollowDefault"] = "跟隨 Windows 預設輸出裝置",
        ["Device_Missing"] = "未連接",
        ["Device_StatusFormat"] = "{0}\n目前格式：{1}  –  {2}",
        ["Group_Tray"] = "系統匣圖示",
        ["Tray_LeftClick"] = "左鍵點一下系統匣圖示時在以下兩種配置間切換",
        ["Tray_And"] = "和",
        ["Tray_Notify"] = "配置變更時顯示通知",
        ["Tray_Hotkey"] = "全域切換快速鍵：",
        ["Tray_HotkeyHint"] = "（點一下後按下組合鍵；Backspace 清除）",
        ["Hotkey_None"] = "無",
        ["Group_Startup"] = "啟動",
        ["Startup_Enable"] = "開機自動啟動（登入時）",
        ["Startup_State_Enabled"] = "已登錄到目前使用者的 Run 機碼。",
        ["Startup_State_Disabled"] = "未登錄。",
        ["Startup_State_Blocked"] = "已登錄，但在「工作管理員 › 啟動應用程式」中被停用。重新勾選即可再次啟用。",
        ["Startup_State_Stale"] = "存在 Run 項目，但指向其他位置。重新勾選即可更新。",
        ["Group_Misc"] = "其他",
        ["Misc_Language"] = "語言：",
        ["Misc_Log"] = "寫入記錄檔",
        ["Misc_OpenLog"] = "開啟記錄資料夾",
        ["Misc_OpenConfig"] = "開啟設定資料夾",

        ["Auto_Enable"] = "啟用自動切換",
        ["Auto_Explain"] = "規則由上而下比對，第一條符合的規則生效。當符合的程式正在執行（或位於前景）時套用其配置；沒有任何規則符合時套用後備配置。手動切換會一直保持，直到規則狀態再次變化。",
        ["Auto_ColProcess"] = "程式",
        ["Auto_ColTrigger"] = "觸發條件",
        ["Auto_ColLayout"] = "配置",
        ["Auto_ColComment"] = "備註",
        ["Auto_Fallback"] = "沒有規則符合時：",
        ["Auto_FallbackNone"] = "不做任何動作",
        ["Auto_Interval"] = "檢查間隔",
        ["Auto_IntervalUnit"] = "秒",

        ["Rule_Title"] = "規則",
        ["Rule_Process"] = "程式：",
        ["Rule_ProcessHint"] = "可執行檔名稱，例如 game.exe。支援萬用字元 * 和 ?。",
        ["Rule_Browse"] = "瀏覽…",
        ["Rule_PickRunning"] = "執行中…",
        ["Rule_Trigger"] = "觸發條件：",
        ["Trigger_Running"] = "執行時",
        ["Trigger_Foreground"] = "位於前景時",
        ["Rule_Layout"] = "配置：",
        ["Rule_Comment"] = "備註：",
        ["Rule_Enabled"] = "啟用此規則",
        ["Rule_ProcessRequired"] = "請輸入程式名稱。",

        ["Picker_Title"] = "選擇正在執行的程式",
        ["Picker_ColProcess"] = "程式",
        ["Picker_ColWindow"] = "視窗標題",
        ["Picker_ShowAll"] = "同時顯示背景處理程序",

        ["Layouts_Explain"] = "勾選的配置會顯示在系統匣選單中。程式會以裝置目前的取樣率和位元深度檢測其是否支援各配置（與 Windows 音效控制台使用相同的測試）。",
        ["Layouts_Supported"] = "✓ 支援",
        ["Layouts_Unsupported"] = "✗ 裝置不接受",
        ["Layouts_Probe"] = "檢測裝置支援情況",
        ["Layouts_Probing"] = "檢測中…",
        ["Layouts_ProbeDone"] = "檢測完成。",
        ["Layouts_CustomLabel"] = "自訂聲道遮罩：",
        ["Layouts_AddCustom"] = "新增",
        ["Layouts_InvalidMask"] = "請輸入聲道遮罩，例如 0x63F（十六進位）或 1599（十進位）。",
        ["Layouts_NeedOne"] = "請至少為系統匣選單選擇一種配置。",
    };
}
